### PR TITLE
reshaping concepts for cognatesets

### PR DESCRIPTION
**Pull request by PaprikaSteiger**

### CODE REVIEW

**Review by Anaphory — CHANGES_REQUESTED** [review]
I just ran the script from this updated branch on my Arawak dataset, and it still glues

    XANTHOSOMA SPP.
to about everything, including some cognatesets where I assume there must be a better solution:

    [-,-]{+XANTHOSOMA SPP.,+}ADAM'S APPLE18,30,,,,

This could have a plethora of reasons, so I'll go digging a bit. But until we know and fix it, that's going to block this PR.

Note, this is a bad review. I haven't actually checked any of the code yet.

**Comment by PaprikaSteiger** [comment]
@Anaphory Did you check that this is not due to the dataset itself? I could imagine something like: when you import, ID is derived from concept name, so they might look exactly the same.
I'm just pretty sure that the code writes whatever is in parameterTable ID column to the concept column of a cognateset.

**Comment by Anaphory** [comment]
I'm not excluding that I did something stupid. But the XANTHOSOMA SPP. are something that occurred in the previous version with bad concepticon/clics connections, so I'm suspicious until proven innocent.

**Comment by PaprikaSteiger** [comment]
Hmm, I'm just surprised that I didn't manage to reproduce this error so far. I will also run everything again on the Arawak data and see if I can reproduce the error this time.

**Comment by Anaphory** [comment]
The issue is here:

https://github.com/Anaphory/lexedata/blob/6b1989ac4f9ad33af3fdf19322605abc219ab7c1/src/lexedata/enrich/guess_concept_for_cognateset.py#L26-L31

The code assumes that every #Parameter has a unique #concepticonReference. That's not necessarily true, eg. in Arawak, very few of the species names have one. So what happens is that 

https://github.com/Anaphory/lexedata/blob/6b1989ac4f9ad33af3fdf19322605abc219ab7c1/src/lexedata/enrich/guess_concept_for_cognateset.py#L20-L25

in `concept_to_concepticon`, a lot of valid concepts keys have value `None`, and then `concepticon_to_concept` maps all these `None` #concepticonReferences to the last one encountered, which happens to be `'XANTHOSOMA SPP.'`

**Review by Anaphory — COMMENTED** [review]
Sorry for the giant rewrite!

**Comment by Anaphory** [comment]
Hey @PaprikaSteiger I largely changed the structure, in particular in terms of functions, of the module. I may have forgotten a case, nearly forgot the case where the #cognatesetReference is in #FormTable, without separate #CognateTable. So it's wise if you have a look.
(I did break the tests, by changing the API. Shall I fix it? Should we fix the tests to fix my changed API, or the API to fit the existing tests? Which version of the API do you prefer?)

**Review by Anaphory — APPROVED** [review]

**Comment by PaprikaSteiger** [comment]
Sorry, haven't seen this comment for some days. I'll have a look at the changes. Then adapt the tests and finally merge this pull request.

**Comment by Anaphory** [comment]
Hi @PaprikaSteiger, I think I have fixed the issues you pointed out I had left in in my hasty rewrite, eg. for missing CLICS. Have a look, please.

**Review by Anaphory — APPROVED** [review]

**Pull request merged**
